### ISSUE TITLE
`If` block with whitespace control is mutated during transform

### ISSUE THREAD

**Issue by tylerturdenpants** [ember-template-lint/ember-template-recast#155]
Given:
```hbs
{{#if foo~}}
  {{foo}}
{{/if}}
```

Expected:
```hbs
{{#if foo~}}
  {{foo}}
{{/if}}
```

Actual:
```hbs
{{#if foo~}}{{foo}}
{{/if}}
```

**Comment by rwjblue** [comment]
Can you submit a failing test case?

**Comment by rwjblue** [comment]
I created https://github.com/wycats/handlebars.js/pull/1584 to make this much nicer. At the moment the text nodes after the whitespace are completely removed from the AST, so we can't easily "fix" the reported problem.

Once that PR lands (and is released) we can:

1. update `handlebars` version in `@glimmer/syntax`
2. tweak the `codemod` option details to use `disableWhitespaceControl` (instead of `ignoreStandalone`)
3. release `@glimmer/syntax`
4. update `@glimmer/syntax` here
5. release an update
